### ISSUE TITLE
Notification > A push notification for a direct group doesn't display the members name

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#314]
# Precondition
Refer to https://github.com/Twake/Twake/issues/489

# Actual Result
When sending a message to the direct group, it pushes a notification. 
The push notification only displays: `<author> in <Workspace_name>`, the user doesn't know exactly which channel has the message.
![IMG_2079](https://user-images.githubusercontent.com/69950655/109787315-adc43400-7c40-11eb-8d2f-a0ab21a4cac2.PNG)

# Expected Result
Please refer to the story then work with our UX designer for the final result.

# Environment
Both iOS and Android App
Build version: 2.2.9

**Comment by bobs4462** [comment]
@RomaricMourgues Hello, Any ideas about this issue, as far as I know direct chats do not have any name, they have dynamic names composed from chat member names, of which there could be many.

**Comment by RomaricMourgues** [comment]
Exactly, and you can get the users information with this API:

```
POST /ajax/users/all/get

{
    id: ["uuid", "uuid", "uuid", "uuid", "uuid"]
}
```

**Comment by bobs4462** [comment]
Yeah that's cool, but we don't need to get users information, @tlle14 is talking about the issue with channel name in notification title, can we dynamically generate channel name for directs (and add it to notification title), before sending the notification or does it require too much hassle, so that we can postpone this issue for better times?

**Comment by tlle14** [comment]
Hi @bobs4462 , that's why it's a minor ticket, save for later.

**Comment by RomaricMourgues** [comment]
Oh sorry I did not understood. It is a Twake issue, currently the format is:

**Author in Company** for direct channels

**ChannelName in Company • Workspace** for workspace channels

**Comment by bobs4462** [comment]
I'm not really sure what I want). Maybe we can add Something like **Author1, Author2...** but only first 20 symbols or so, so that it won't become messy

**Comment by tlle14** [comment]
> Oh sorry I did not understood. It is a Twake issue, currently the format is:
> 
> **Author in Company** for direct channels
> 
> **ChannelName in Company • Workspace** for workspace channels
> 
> You want something like **Author1, Author2, Author3 in Company** ?

Hi @RomaricMourgues , the issue is about how we display a notification for a direct group
Example: the direct group has: member1, member2, member3, member4
When member1 sending a message to the group, how the notification will display?

**Comment by RomaricMourgues** [comment]
For now if I remember it will display just "Sender in Company" as title.
We'll change this title to "Member1, Member2 and Member3 in Company".

The text is always like this anyway: "[member name]: the message"

**Comment by bobs4462** [comment]
Alright, thanks, that will do :)

**Comment by bobs4462** [comment]
@tlle14 I think this one has been fixed (on production at least)

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue is not fixed
As in this photo, It should be:
```
Ha Nguyen, Hieu Hoang, Tung Lam Le Cao, ... in LINAGORA
Tung Lam Le Cao: ahihihihi 
```

**Comment by RomaricMourgues** [comment]
We still not implemented this update, it should be done in some weeks.
It is something only backend Twake can do :)

**Comment by tlle14** [comment]
I should close this ticket since it is the backend issue
