### ISSUE TITLE
Notification > Triple push notifications when having a new direct message

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#421]
# Actual Result
On Production Server, this bug is quite random. When a user sends a direct message, it displays 3 notifications for a new message.
![image](https://user-images.githubusercontent.com/69950655/113990241-736f3780-987b-11eb-9e8c-47a24e9e1a67.png)

Sometimes push notifications aren't sent to the user. 

# Expected Result
The push notification should work more stable. Each new message should have 1 push notification.

# Environment
Both iOS and Android app
Build version: 2.2.9-5

**Comment by RomaricMourgues** [comment]
Can you give me your user email for me to check you have only only token for your user ?

Also the other users emails in the direct channel.

(You can send it to me via Twake)

**Comment by RomaricMourgues** [comment]
Is it happening everytime or just randomly ?

**Comment by tlle14** [comment]
> Is it happening everytime or just randomly ?

Just randomly. It happens 2/3 times for me, with the user that I direct to for the first time.

**Comment by RomaricMourgues** [comment]
Ok, interesting thanks

**Comment by bobs4462** [comment]
@tlle14 Have you noticed recently that this bug still occurs?

**Comment by tlle14** [comment]
Hi @bobs4462 
The issue seems to no longer happen, did you fix anything?

**Comment by bobs4462** [comment]
@tlle14 Hi, I think it was fixed along the way with other updates on QA server

**Comment by RomaricMourgues** [comment]
I did not fix it, it is linked to the usage of PHP for rabbitmq consumer, the issue will randomly appear on QA and prod until we migrate it to nodejs (no impact on mobile)
