### ISSUE TITLE
Unread counter for a channel always starts at 2

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#651]
# Actual Result
An unread counter for a channel always starts at "2"

# Expected Result
It should start at 1

# Environment
Build version: 3.0.0
Device: Samsung Galaxy A51 - Android 11 - 6.5 inch
QA environment

**Comment by bobs4462** [comment]
Fixed, should be ok, in the next build

**Comment by tlle14** [comment]
Hi @bobs4462 
Retest failed!
I don't see an unread counter when having a new message 
https://images.zenhubusercontent.com/309637937/e892522a-d4b8-4273-bf22-2f750965eae3/videof6bc093d_3cd7_48ba_8fbf_0c9b197c3e0cvideo.mp4

**Comment by tlle14** [comment]
Hi @EvGen94 
Retest failed!
I still don't see the unread counter

**Comment by bobs4462** [comment]
That's strange, ok let me investigate more thoroughly then

**Comment by tlle14** [comment]
Sorry @bobs4462 
That was my test data having a problem with mention. 
Retest is "so pass"!
